(function () {
  'use strict';

  window.ThreadveilDefaults = {
    signalMeta: [
      { id: 'emojiMidWordRe', label: '词中插入 emoji', def: 6 },
      { id: 'midWordEmoji', label: '拆词 emoji', def: 5 },
      { id: 'emojiOverload', label: '大量 emoji', def: 5 },
      { id: 'emojiSeparatedMention', label: '模板文案 + emoji + @', def: 6 },
      { id: 'emptyContentWithEmoji', label: '短字符 + emoji', def: 6 },
      { id: 'emojiBomb', label: 'emoji 轰炸', def: 5 },
      { id: 'highEmojiDensity', label: 'emoji 密度过高', def: 3 },
      { id: 'externalLinks', label: '外部链接', def: 5 },
      { id: 'anyLink', label: '短回复含链接', def: 4 },
      { id: 'promotionMention', label: '引流 @', def: 4 },
      { id: 'templatePhrases', label: '模板文案', def: 4 },
      { id: 'hornyEmoji', label: '暗示性 emoji', def: 2 },
      { id: 'autoGenHandle', label: '随机用户名', def: 2 },
      { id: 'handleStartsWithNumber', label: '数字开头用户名', def: 2 },
      { id: 'emojiName', label: '昵称 emoji 过多', def: 2 },
      { id: 'unicodeDeco', label: '特殊装饰字符', def: 2 },
      { id: 'extremeContent', label: '敏感内容词库', def: 6 },
      { id: 'atMentions', label: '多次 @ 他人', def: 1 },
      { id: 'shortReply', label: '短句回复', def: 1 },
    ],

    ruleConfig: {
      shortReplyMaxChars: 4,
      anyLinkMaxChars: 80,
      emojiOverloadMin: 8,
      emojiBombMin: 3,
      emojiBombMaxChars: 60,
      highEmojiDensityMin: 3,
      highEmojiDensityRatio: 0.25,
      promotionMentionMaxChars: 80,
      promotionMentionMinEmoji: 2,
      useDefaultTemplates: true,
      useDefaultExtremeKeywords: true,
      useDefaultExternalLinks: true,
      externalLinkPatterns: [
        't\\.me/',
        't\\.cn/',
        'bit\\.ly/',
        'linktr\\.ee/',
        'beacons\\.ai/',
        'onlyfans\\.com',
        'fansly\\.com',
        'discord\\.gg/',
        'm\\.e/',
        'pan\\.quark\\.cn/',
        'pan\\.baidu\\.com/',
        'lanzou\\w\\.com/',
        'weixin\\.qq\\.com/',
        'v\\.douyin\\.com/',
        'xhslink\\.com',
      ],
      templatePhrases: [
        '私信',
        '看主页',
        '点主页',
        '主页有',
        '线下',
        '免费',
        '约吗',
        '哥哥',
        '湿了',
        '想要',
        '陪我',
        '骚',
        '破处',
        '大秀',
        '露脸',
        '直播',
        '加我微信',
        '加我Q',
        '比她好看',
        '没人比她',
        'i miss the sound',
        'thoughts of you',
        'kissed me good',
        'carry your memory',
        'love is a journey',
      ],
      templateRegexes: [
        '线下.{0,20}骚',
        '线下.{0,20}sao',
        '[就都].{0,3}[日干].{0,3}过',
        '👉\\s*@\\w+',
        '[a-z0-9]\\s*线下',
        '\\Bsao\\b',
      ],
      extremeKeywords: [
        '母狗',
        '找主人',
        '求调教',
        '求操',
        '想被操',
        '求草',
        '骚母狗',
        '发情',
        '求虐',
        '想被艹',
        '母畜',
        '贱狗',
        '求约',
        '文爱',
        '语爱',
        '裸聊',
        '自慰',
        '骚货',
        '单男',
        '约炮',
      ],
      suggestiveEmojiChars: '💦🍑🥵👉👈🔥😈👅🍆',
    },
  };
})();
